import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { Building2, ShieldCheck, UserCheck, ArrowRight, ClipboardCheck, } from 'lucide-react';
import { PageContainer } from '@/components/layout/PageContainer';
import { Button } from '@/components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle, } from '@/components/ui/Card';
export function AdminDashboard() {
    return (_jsxs(PageContainer, { title: "System Administration", description: "Manage BloodBridge verification actions for donor and hospital profiles.", children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsxs(Card, { className: "border-indigo-100", children: [_jsx(CardHeader, { className: "bg-indigo-50/50 border-b border-indigo-100", children: _jsxs(CardTitle, { className: "flex items-center gap-2 text-indigo-900", children: [_jsx(UserCheck, { className: "w-5 h-5 text-indigo-600" }), "Donor Verification"] }) }), _jsxs(CardContent, { className: "p-6", children: [_jsx("p", { className: "text-sm text-slate-600 leading-relaxed", children: "Verify a donor profile using its donor profile ID. Verification enables the donor to participate in BloodBridge matching workflows." }), _jsx(Link, { to: "/admin/donors", className: "inline-block mt-5", children: _jsx(Button, { variant: "primary", size: "sm", rightIcon: _jsx(ArrowRight, { className: "w-4 h-4" }), children: "Verify Donor" }) })] })] }), _jsxs(Card, { className: "border-teal-100", children: [_jsx(CardHeader, { className: "bg-teal-50/50 border-b border-teal-100", children: _jsxs(CardTitle, { className: "flex items-center gap-2 text-teal-900", children: [_jsx(Building2, { className: "w-5 h-5 text-teal-600" }), "Hospital Verification"] }) }), _jsxs(CardContent, { className: "p-6", children: [_jsx("p", { className: "text-sm text-slate-600 leading-relaxed", children: "Verify or revoke verification for a hospital profile using its hospital profile ID." }), _jsx(Link, { to: "/admin/hospitals", className: "inline-block mt-5", children: _jsx(Button, { variant: "primary", size: "sm", rightIcon: _jsx(ArrowRight, { className: "w-4 h-4" }), children: "Manage Hospital" }) })] })] })] }), _jsx(Card, { className: "border-slate-200", children: _jsx(CardContent, { className: "p-6", children: _jsxs("div", { className: "flex items-start gap-4", children: [_jsx("div", { className: "w-11 h-11 rounded-xl bg-emerald-50 text-emerald-600 flex items-center justify-center shrink-0", children: _jsx(ShieldCheck, { className: "w-5 h-5" }) }), _jsxs("div", { children: [_jsx("h3", { className: "text-sm font-bold text-slate-900", children: "Backend Verification Controls" }), _jsx("p", { className: "text-xs text-slate-500 mt-1 leading-relaxed", children: "The current Spring Boot backend exposes verification actions directly, but does not expose admin listing or statistics endpoints. This dashboard therefore only presents actions supported by the current API contract." }), _jsxs("div", { className: "flex items-center gap-2 mt-4 text-xs text-slate-600", children: [_jsx(ClipboardCheck, { className: "w-4 h-4 text-emerald-600" }), "Verification actions use the authenticated ADMIN role."] })] })] }) }) })] }));
}
